blank_issues_enabled: false
contact_links:
  - name: ğŸª²Bug report
    about: What needs fixing?
    url: https://github.com/comarev/comarev/issues/new?template=bug_report.md&projects=comarev/comarev/1
  - name: ğŸ’¡Feature request
    about: What needs building?
    url: https://github.com/comarev/comarev/issues/new?template=feature_request.md&projects=comarev/comarev/1
  - name: ğŸ“„Documentation addition/change
    about: What needs documenting?
    url: https://github.com/comarev/comarev/issues/new?template=documentation.md&projects=comarev/comarev/1
  - name: ğŸ§¹Chore
    about: What needs updating or removing?
    url: https://github.com/comarev/comarev/issues/new?template=chore.md&projects=comarev/comarev/1
