blank_issues_enabled: false
contact_links:
  - name: ğŸª²Bug report
    about: ğŸ”¨What needs fixing? âœ¨
    url: https://github.com/comarev/comarev/issues/new?template=bug_report.md&projects=comarev/comarev/1
  - name: ğŸ’¡Feature request
    about: ğŸ”¨What needs building? âœ¨
    url: https://github.com/comarev/comarev/issues/new?template=feature_request.md&projects=comarev/comarev/1
  - name: ğŸ“„Documentation addition/change
    about: ğŸ”¨What needs documenting? âœ¨
    url: https://github.com/comarev/comarev/issues/new?template=documentation.md&projects=comarev/comarev/1
  - name: ğŸ§¹Chore
    about: ğŸ”¨What needs updating or removing? âœ¨
    url: https://github.com/comarev/comarev/issues/new?template=chore.md&projects=comarev/comarev/1
  - name: ğŸ™Problem Validation
    about: ğŸ”¨Describe a stakeholder's issueâœ¨
    url: https://github.com/comarev/comarev/issues/new?template=problem_validation.md&projects=comarev/comarev/1
